### ISSUE TITLE
Table rerender infinitely with non-zero padding for left and right

### ISSUE THREAD

**Issue by rajasegar** [vincjo/svelte-simple-datatables#55]
If i set the following style for my `td`
```css 
td { text-align: center; padding: 4px 2px; }
```
the component is rerendering and goes on expading overflowing the page width
<img width="1651" alt="Screenshot 2022-06-29 at 4 19 15 PM" src="https://user-images.githubusercontent.com/2083049/176419171-910239d7-8d98-49a5-9284-d6d5d8039e5e.png">
