### ISSUE TITLE
Unable to apply styles to component

### ISSUE THREAD

**Issue by ProphetLamb** [vincjo/svelte-simple-datatables#74]
Thanks for the easy-to-use control. I have been trying to integrate the control with a style manager, but had limited success so far:

![much styles](https://user-images.githubusercontent.com/19748542/194651544-0b42899a-3fbd-47e5-a61d-dff98371ec96.png)

After attempting a few elegant solutions, such as specifying the `background-color` and similar properties targeting `<Datatable class="themed-datatable"` using the custom style `themed-datatable` which specifies `background-color` (the normal way of styling) I gave up. Nothing could change the background or borders. 

So I resorted to the bad  `:global(*)` selector in order to theme any thing at all. This is what you can see in the screenshot above. 

```scss
  :global(*) {
    background-color: var(--theme-colors-background, initial);
    border-bottom: var(--theme-colors-background-contrast, initial);
  }
```

I remain unable to theme certain elements because of the following nasty class `.css` that I cannot overwrite.

![image](https://user-images.githubusercontent.com/19748542/194651882-7a74b71e-3feb-4cd2-8d98-6f2174ed3c57.png)

CSS is not my daily bread and butter, so I might be missing something obvious. Any suggestions on how I can get the component themed? 

Thanks in advance. Cheers!
